#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="${ROOT_DIR}/.venv-build"
DIST_DIR="${ROOT_DIR}/dist/build"
WORK_DIR="${ROOT_DIR}/dist/pyinstaller-work"
BUILDINFO_FILE="${ROOT_DIR}/taco_tool/_generated_buildinfo.py"
PYTHON_BIN="${TACO_BUILD_PYTHON_BIN:-python3.12}"

VERSION="${TACO_BUILD_VERSION:-$(git describe --tags --always --dirty)}"
dirty_suffix=""
if [[ -n "$(git status --porcelain)" ]]; then
  dirty_suffix="-dirty"
fi
COMMIT="${TACO_BUILD_COMMIT:-$(git rev-parse --short=12 HEAD)${dirty_suffix}}"
BUILT_AT="${TACO_BUILD_AT:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
DIRTY_PY=False
if [[ "${COMMIT}" == *"-dirty" ]]; then
  DIRTY_PY=True
fi

if ! command -v "${PYTHON_BIN}" >/dev/null 2>&1; then
  echo "${PYTHON_BIN} is required to build taco." >&2
  exit 1
fi

rm -rf "${DIST_DIR}" "${WORK_DIR}"
mkdir -p "${DIST_DIR}" "${WORK_DIR}"

cat > "${BUILDINFO_FILE}" <<EOF
# Generated by scripts/build_binary_pyinstaller.sh
VERSION = "${VERSION}"
COMMIT = "${COMMIT}"
BUILT_AT = "${BUILT_AT}"
DIRTY = ${DIRTY_PY}
EOF

"${PYTHON_BIN}" -m venv "${VENV_DIR}"
# shellcheck disable=SC1090
source "${VENV_DIR}/bin/activate"

python -m pip install --upgrade pip
pip install -e "${ROOT_DIR}"
pip install pyinstaller
python -m spacy download en_core_web_sm

pyinstaller \
  --noconfirm \
  --clean \
  --onefile \
  --name taco \
  --paths "${ROOT_DIR}" \
  --collect-submodules taco_tool \
  --collect-data taco_tool \
  --hidden-import taco_tool \
  --hidden-import taco_tool.cli \
  --collect-all spacy \
  --collect-all en_core_web_sm \
  --collect-all chardet \
  --collect-all thinc \
  --collect-all srsly \
  --collect-all preshed \
  --collect-all cymem \
  --collect-all blis \
  --collect-all catalogue \
  --hidden-import en_core_web_sm \
  --distpath "${DIST_DIR}" \
  --workpath "${WORK_DIR}" \
  --specpath "${WORK_DIR}" \
  "${ROOT_DIR}/scripts/taco_entrypoint.py"

chmod +x "${DIST_DIR}/taco"
echo "Built binary: ${DIST_DIR}/taco"
echo "Build version: ${VERSION}"
echo "Build commit: ${COMMIT}"
echo "Built at: ${BUILT_AT}"
